services:
  backend:
    build: ./backend
    ports:
      - "5050:5000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend
